---
# Source server information.
source_hostname: barnet.localdomain
source_short_hostname: barnet
source_ip_address: 192.168.100.50



# Target server information
target_hostname: orademovm.publicsubnet.demovcn.oraclevcn.com
target_short_hostname: orademovm
target_ip_address: 130.61.129.186

#Source 

#source_grid_base: 
#source_grid_home: 
#source_grid_sid: 
source_oracle_sid: cdbt
source_ora_inventory: /u01/app/oraInventory
source_oracle_base: /u01/app/oracle
source_oracle_home: /u01/app/oracle/product/21.0.0/dbhome_1
source_xtts_stage_dir: /home/oracle/xtts_stage
source_xtts_scripts_dir: /home/oracle/xtts
source_xtts_scratch_dir: /u03/app/oracle/xtts_scratch
source_dp_dir: /u03/app/oracle/dump
source_pdb: pdb_test
source_srv: pdb_test
source_sys_user: sys
source_sys_passwd: Rosha1989
source_system_passwd: Rosha1989
source_conn_str: "{{source_sys_user}}/{{source_sys_passwd}}@{{source_srv}}"
source_oracle_passwd: Oracle123





#Target 
target_oracle_sid: MIGCDB
target_db_unique_name: MIGCDB_5x9_fra
target_pdb_guid: 0A0C783A9C085375E063A701000AABFF
target_grid_base: /u01/app/grid
target_grid_home: /u01/app/23.0.0.0/grid
target_ora_inventory: /u01/app/oraInventory
target_grid_sid: ASM1
target_oracle_base: /u01/app/oracle
target_oracle_home: /u01/app/oracle/product/23.0.0.0/dbhome_1
target_xtts_stage_dir: /home/oracle/xtts_stage
target_xtts_scripts_dir: /home/oracle/xtts
target_xtts_scratch_dir: /u01/app/oracle/xtts_scratch
target_dp_dir: /u01/app/oracle/dump
target_data_dg: DATA
target_pdb: pdb_test
target_srv: pdb_test
target_sys_user: sys
target_sys_passwd: CloudDBA2023##
target_system_passwd: CloudDBA2023##
target_conn_str: "{{target_sys_user}}/{{target_sys_passwd}}@{{target_srv}}"
target_oracle_passwd: CloudDBA2023##

# source coma separated user tablespaces list
tablespaces: HR_TBS,CO_TBS

#xtt  parameters
rman_xttconvert: rman_xttconvert_VER4.3.zip

source_platform_id: 13   ## can be obtained from V$DATABASE.PLATFORM_ID
parallel: 2
rollparallel: 2
getfileparallel: 2
metatransfer: 1
dest_user: oracle
usermantransport: 1

# source metadata export parameters

full: y
transportable: always
dumpfile: meta_exp_%U.dmp
filesize: 1GB
metrics: y
logtime: all
exclude_stats: TABLE_STATISTICS,INDEX_STATISTICS
exclude_tbs: TABLESPACE:"IN('TEMP','USERS')"
exclude_schemas: SCHEMA:"IN('ORDSYS','ORACLE_OCM','ORDDATA','SI_INFORMTN_SCHEMA')"
dump_dir: dump
exp_logfile: meta_exp.log
exp_par_file: meta_export.par

#target metadata import parameters

imp_logfile: meta_imp.log
imp_par_file: meta_import.par