---
# tasks file for post_mig_check

- name: run utlrp.sql
  shell: |
    export ORACLE_SID={{target_oracle_sid}}
    export ORACLE_HOME={{target_oracle_home}}
    cd {{target_oracle_home}}/rdbms/admin
    echo -e '@utlrp.sql' |{{ target_oracle_home }}/bin/sqlplus -s {{target_conn_str}} as sysdba 
  register: utl_out

- name: display utlrp log
  debug:
    msg: "{{utl_out.stdout_lines}}"

  


- name: run the verification scripts capture the target db objects details 
  shell: |
    export ORACLE_SID={{target_oracle_sid}}
    export ORACLE_HOME={{target_oracle_home}}
    cd {{target_verification_dir}}
    echo -e '@{{ item }}' |{{ target_oracle_home }}/bin/sqlplus -s {{target_conn_str}} as sysdba 
  with_items: 
      - "{{target_verification_dir}}/Application_Objects_In_System_Sysaux.sql"
      - "{{target_verification_dir}}/DB_Links_Details.sql"
      - "{{target_verification_dir}}/Granted_Roles.sql"
      - "{{target_verification_dir}}/Invalid_Objects.sql"
      - "{{target_verification_dir}}/List_Schemas_And_Default_TBS.sql"
      - "{{target_verification_dir}}/Object_Count_Per_Schema.sql"
      - "{{target_verification_dir}}/Schedules_jobs.sql"
  register: sql_out

- name: display sql_out
  debug: 
     msg: "{{item.stdout_lines}}"
  with_items: "{{sql_out.results}}"


- name: take database statistics
  shell: |
    export ORACLE_SID={{target_oracle_sid}}
    export ORACLE_HOME={{target_oracle_home}}
    echo -e "SET PAGESIZE 0 VERIFY OFF HEADING OFF ECHO OFF\n {{item}};" | {{ target_oracle_home }}/bin/sqlplus -s {{target_conn_str}} as sysdba  
  register: statistics_out
  with_items: 
     - "exec dbms_stats.gather_dictionary_stats"
     - "EXEC DBMS_STATS.gather_database_stats( method_opt => 'FOR ALL COLUMNS SIZE AUTO',estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE,cascade=>TRUE,degree => 16)"

    
- name: display statistics_out
  debug: 
    msg: "{{statistics_out.results}}"