## primary database variables

pri_region: uk-london-1
pri_vm_cluster_display_name: pri_vmcluster1_example
pri_vm_cluster_id: ocid1.vmcluster.oc1..xxxxxxEXAMPLExxxxxx

pri_cluster_name: cluster01
pri_scan_name: "{{cluster_name}}-scan"
pri_scan_fq_name: "{{ scan_name}}.{{ domain_name}}"
pri_scan_port: 1521

db_name: cdbpoc
pri_db_unique_name: {{db_name}}_{{pri_region}}
admin_password: POCDBA

pri_oracle_sid1: cdbpoc1  #node1
pri_oracle_sid2: cdbpoc2  #node2


## standby database variables

stby_region: uk-cardiff-1
stby_vm_cluster_display_name: stby_vmcluster1_example
stby_db_unique_name: {{db_name}}_{{stby_region}}

