- name: Configure Migration prerequisites
  hosts: migration_vms
  tags: mig_prereqs
  vars_files: host_vars/mig_vars.yml
  become: true
  become_user: oracle
  roles:
    - mig_prereqs

- name: do level 0 backup on {{source_hostname}}
  hosts: onprem_vm
  tags: level_0_backup
  vars_files: host_vars/mig_vars.yml
  become: true
  become_user: oracle
  roles:
    - level_0_backup

- name: do level 0 restore on {{target_hostname}}
  hosts: target_oci_vm
  tags: level_0_restore
  vars_files: host_vars/mig_vars.yml
  become: true
  become_user: oracle
  roles:
    - level_0_restore
