---
# Source server information. (AWS)
source_hostname: ip-10-1-7-196.eu-west-2.compute.internal
source_short_hostname: ip-10-1-7-196
source_ip_address: 18.132.139.140



# Target server information (OCI)
target_hostname: orademovm.publicsubnet.demovcn.oraclevcn.com
target_short_hostname: orademovm
target_ip_address: 130.61.129.186

#Source 

#source_grid_base: 
#source_grid_home: 
#source_grid_sid: 
source_oracle_sid: cdb1
source_ora_inventory: /u01/app/oraInventory
source_oracle_base: /u01/app/oracle
source_oracle_home: /u01/app/oracle/product/19.0.0/dbhome_1
source_dp_dir: /u01/app/oracle/{{source_pdb}}_dump
source_verification_dir: /home/oracle/{{source_pdb}}_verification
source_pdb: pdb2
source_srv: pdb2
source_sys_user: sys
source_sys_passwd: CloudDBA2023##
source_system_passwd: CloudDBA2023##
source_conn_str: "{{source_sys_user}}/{{source_sys_passwd}}@{{source_srv}}"
source_streams_pool_size: 100M
#source_oracle_passwd: Oracle123





#Target 
target_oracle_sid: MIGCDB
target_db_unique_name: MIGCDB_5x9_fra
target_pdb_guid: 0BECFCF0555D87C9E063A701000AFF6F
target_grid_base: /u01/app/grid
target_grid_home: /u01/app/23.0.0.0/grid
target_ora_inventory: /u01/app/oraInventory
target_grid_sid: ASM1
target_oracle_base: /u01/app/oracle
target_oracle_home: /u01/app/oracle/product/23.0.0.0/dbhome_1
target_dp_dir: /u01/app/oracle/{{target_pdb}}_dump
target_verification_dir: /home/oracle/{{target_pdb}}_verification
target_data_dg: DATA
target_pdb: pdb2
target_srv: pdb2
target_sys_user: sys
target_sys_passwd: CloudDBA2023##
target_system_passwd: CloudDBA2023##
target_conn_str: "{{target_sys_user}}/{{target_sys_passwd}}@{{target_srv}}"
target_oracle_passwd: CloudDBA2023##
target_streams_pool_size: 100M


#Full exp/imp parameters





# source metadata export parameters

full: y
dumpfile: full_exp_{{source_short_hostname}}_{{source_pdb}}_%L.dmp
filesize: 1GB
metrics: y
logtime: all
exclude_stats: statistics
exclude_tbs: TABLESPACE:"IN('TEMP')"
exclude_schemas: SCHEMA:"IN('ORDSYS','ORACLE_OCM','ORDDATA','SI_INFORMTN_SCHEMA')"
source_dump_dir: "{{source_pdb}}_dp_dump"
exp_logfile: full_export_{{source_pdb}}.log
exp_par_file: full_export_{{source_pdb}}.par
access_method: automatic
flashback_time: systimestamp
exp_parallel: 2
dest_user: oracle
compression: metadata_only ##  metadata_only does not require Advanced Compression Option
exp_job_name: exp_{{source_short_hostname}}_{{source_pdb}}
#target metadata import parameters
imp_parallel: 2
imp_logfile: full_import_{{target_pdb}}.log
imp_par_file: full_import_{{target_pdb}}.par
transform_lob: lob_storage:securefile
imp_job_name: imp_{{target_short_hostname}}_{{target_pdb}}
target_dump_dir: "{{target_pdb}}_dp_dump"

gpg_password: CloudDBA2023##  ## gpg encryption