---
# tasks file for target_pre_character_set_check


- block:
    - name: check database character set and national character set on the {{target_srv}}
      shell: |
        export ORACLE_SID={{target_oracle_sid}}
        export ORACLE_HOME={{target_oracle_home}}
        export TNS_ADMIN={{target_tns_admin}}
        echo -e "SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF\n select property_name, property_value from database_properties where property_name in ('NLS_CHARACTERSET', 'NLS_NCHAR_CHARACTERSET');" | {{ target_oracle_home }}/bin/sqlplus -s {{target_conn_str}} as sysdba
      register: target_cha_out

    - name: display the target character set output
      debug:
       msg: 
         - "{{target_cha_out.stdout_lines}}"
        # - "{{source_cha_out.stdout_lines}}"
    - name: store the target characterset value in a local file
      become: true
      become_user: ansibleadmin
      copy: 
        content: "{{target_cha_out.stdout_lines}}"
        dest: "{{target_pdb}}_target_cha_set.txt"
      delegate_to: localhost
