---
# tasks file for oracle_create_db

- name: Check if data directory already exists
  stat:
    path: "{{ data_dir }}/{{ oracle_sid|upper }}"
  register: db_result

- name: create Oracle CDB & a PDB
  shell: "{{ software_dir }}/oracle_create_database.sh >> {{ software_dir }}/create_db_{{ ansible_date_time.iso8601 }}.log"
  when: not db_result.stat.exists

- name: check if database has already been set to archivelog mode
  tags: set_archivelog_mode
  shell: export ORACLE_HOME={{ oracle_home }}; export ORACLE_SID={{ oracle_sid }}; export PATH=$PATH:$ORACLE_HOME/bin; echo -e "SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF\n select log_mode from v\$database;" | {{ oracle_home }}/bin/sqlplus -s / as sysdba
  register: archive_mode

- name: Display the archive mode
  tags: set_archivelog_mode
  debug: 
    var: archive_mode.stdout 

- name: set database to archivelog mode
  tags: set_archivelog_mode
  shell: "{{ scripts_dir }}/set_archivelog_mode.sh >> {{ scripts_dir }}/set_archivelog_mode_{{ ansible_date_time.iso8601 }}.log"
  when: archive_mode.stdout == "NOARCHIVELOG"
