---
# tasks file for grid_root_scripts
#
# - name: check if oratab has +ASM entry on item
#   lineinfile:
#      path: /etc/oratab
#      #line: "+ASM:/u01/app/"
#      search_string: "+ASM"
#      state: present
#   check_mode: yes
#   register: asm_out
#   ignore_errors: true

# - name: check +ASM entry exists in /etc/oratab
#   shell: grep "^+ASM" /etc/oratab
#   register: asm_out
#   ignore_errors: true
#   tags: grid_root_scripts
# #- debug: var=asm_out

- name: check if grid has already been configured
  shell: . {{grid_scripts_dir }}/setEnv.sh; crsctl check cluster
  register: cluster_out
  ignore_errors: true
  changed_when: false


# first run the root scripts on node 1
- name: Run Oracle root scripts on node1
  shell: "{{ grid_software_dir }}/grid_root_scripts.sh > {{ grid_software_dir }}/root_scripts.log"
  when: (cluster_out.rc != 0) and  (inventory_hostname in groups['oracle_rac_ol8_21c_node1'])
  tags: grid_root_scripts

- name: Run Oracle root scripts on node2
  shell: "{{ grid_software_dir }}/grid_root_scripts.sh > {{ grid_software_dir }}/root_scripts.log"
  when: (cluster_out.rc != 0) and  (inventory_hostname in groups['oracle_rac_ol8_21c_node2'])
  tags: grid_root_scripts

