
  ## primary_vm_cluster
- name: get the primary vm_cluster_ocid from the cluster display name
  oci_database_vm_cluster_facts:
      lifecycle_state: AVAILABLE
      display_name: {{pri_vm_cluster_display_name}}
      region: {{pri_region}}
  register: pri_cluster_out

- name: display pri_cluster_out
  debug: var=pri_cluster_out.vm_clusters

- set_fact:
  pri_vm_cluster_id: {{pri_cluster_out.vm_clusters.id}}

  ## primary db_home_id details
- name: get the primary db_home_id 
  oci_database_db_home_facts:
      vm_cluster_id: {{pri_vm_cluster_id}}
      lifecycle_state: AVAILABLE
      display_name: {{pri_db_home_display_name}}
      region: {{pri_region}}
  register: pri_db_home_out

- name: display pri_db_home_out
  debug: var=pri_db_home_out.db_homes

- set_fact:
  pri_db_home_id: {{pri_db_home_out.db_homes.id}}
            
         
- name: build primary database
  oci_database_database:
             # required
    db_home_id: "ocid1.dbhome.oc1..xxxxxxEXAMPLExxxxxx"
    compartment_id: "ocid1.compartment.oc1..xxxxxxEXAMPLExxxxxx"
    region: {{pri_region}}
    wait: yes
    wait_timeout: 14400
    database:
       admin_password: example-password
       db_name: {{db_name}} 
       db_unique_name: db_name_{{pri_region}}   
       pdb_name: pdb_name_example
       character_set: character_set_example
       ncharacter_set: ncharacter_set_example
       db_workload: OLTP
       freeform_tags: {'Department': 'Automation'}
       defined_tags: {'Operations': {'CostCenter': 'POC'}}
    register: pri_out
    check_mode: yes
      
   - name: display pri_out
     debug: var=pri_out.database

#  - set_fact:
#    pri_database_id: {{pri_out.database.id}}
    
       