---
# tasks file for level_0_restore

- name: check if backup files have been arrived to {{target_hostname}}
  find:
    paths: "{{target_xtts_scratch_dir}}/"
  register: filesFound

- fail: 
    msg: " The {{target_xtts_scratch_dir}} is empty"
  when: filesFound.matched == 0

- debug:
    msg: 
     - "Backups found. Proceeding.."
     - "filesFound.stdout_lines"
  when: filesFound.matched > 0
     

- name: check res.txt file is available on  {{target_xtts_scratch_dir}}
  stat: 
    path: "{{target_xtts_scratch_dir}}/res.txt"
  register: res_out

- fail: 
    msg: " res.txt file can not be found"
  when: not res_out.stat.exists

- name: copy res.txt file to {{target_xtts_scripts_dir}}
  command: cp {{target_xtts_scratch_dir}}/res.txt {{target_xtts_scripts_dir}}/res.txt
  when: res_out.stat.exists

## level_0 restore

- name: do level 0 resore on {{target_hostname}}
  shell: |
    export TMPDIR={{target_xtts_scripts_dir}}
    export ORACLE_SID={{target_oracle_sid}}
    export ORACLE_HOME={{target_oracle_home}}
    cd {{target_xtts_scripts_dir}}
    {{target_oracle_home}}/perl/bin/perl xttdriver.pl --restore
  register: restore_out

- name: validate if the restore has been completed.
  debug: 
    msg:
    - "Level 0 restore has now been completed"
    - "{{restore_out.stdout_lines}}"
  when: restore_out.rc == 0

  