---
# Source server information. (AWS)
source_hostname: ip-10-1-7-196.eu-west-2.compute.internal
source_short_hostname: ip-10-1-7-196
source_ip_address: 18.132.139.140



# Target server information (OCI)
target_hostname: db-system-hostname1.subnetdns.sampletestdns.oraclevcn.com
target_short_hostname: db-system-hostname1
target_ip_address: 130.61.108.46

#Source 

#source_grid_base: 
#source_grid_home: 
#source_grid_sid: 
source_oracle_sid: cdb1
source_ora_inventory: /u01/app/oraInventory
source_oracle_base: /u01/app/oracle
source_oracle_home: /u01/app/oracle/product/19.0.0/dbhome_1
source_xtts_stage_dir: /home/oracle/{{source_pdb}}_xtts_stage
source_xtts_scripts_dir: /home/oracle/{{source_pdb}}_xtts
source_xtts_scratch_dir: /u01/app/oracle/{{source_pdb}}_xtts_scratch
source_dp_dir: /u01/app/oracle/{{source_pdb}}_dump
source_verification_dir: /home/oracle/{{source_pdb}}_verification
source_pdb: pdb_oci
source_srv: pdb_oci
source_sys_user: sys
source_sys_passwd: CloudDBA2023##
source_system_passwd: CloudDBA2023##
source_conn_str: "{{source_sys_user}}/{{source_sys_passwd}}@{{source_srv}}"
#source_oracle_passwd: Oracle123





#Target 
target_oracle_sid: sampledb1
target_db_unique_name: SAMPLEDB_845_FRA
target_pdb_guid: 0E223FBD7A95E5EDE06380011EACACBE
target_grid_base: /u01/app/grid
target_grid_home: /u01/app/19.0.0.0/grid
target_ora_inventory: /u01/app/oraInventory
target_grid_sid: ASM1
target_oracle_base: /u01/app/oracle
target_oracle_home: /u01/app/oracle/product/19.0.0.0/dbhome_1
target_xtts_stage_dir: /home/oracle/{{target_pdb}}_xtts_stage
target_xtts_scripts_dir: /home/oracle/{{target_pdb}}_xtts
target_xtts_scratch_dir: /source_backup/{{target_pdb}}_xtts_scratch
target_dp_dir: /source_backup/{{target_pdb}}_dump
target_verification_dir: /home/oracle/{{target_pdb}}_verification
target_data_dg: DATA
target_pdb: pdb_oci
target_srv: mig_serv_pdb_oci                                ##tns name for the target service
target_sys_user: sys
target_sys_passwd: CloudDBA2023##
target_system_passwd: CloudDBA2023##
target_conn_str: "{{target_sys_user}}/{{target_sys_passwd}}@{{target_srv}}"
##target_oracle_passwd: CloudDBA2023##

# source coma separated user tablespaces list
tablespaces: HR_TBS,CO_TBS,SH_TBS,USERS

#xtt  parameters
rman_xttconvert: rman_xttconvert_VER4.3.zip

source_platform_id: 13   ## can be obtained from V$DATABASE.PLATFORM_ID
parallel: 4
rollparallel: 2
getfileparallel: 2
metatransfer: 1
dest_user: oracle
usermantransport: 1

# source metadata export parameters

full: y
transportable: always
dumpfile: meta_exp_%U.dmp
filesize: 1GB
metrics: y
logtime: all
exclude_stats: TABLE_STATISTICS,INDEX_STATISTICS
exclude_tbs: TABLESPACE:"IN('TEMP')"
exclude_schemas: SCHEMA:"IN('ORDSYS','ORACLE_OCM','ORDDATA','SI_INFORMTN_SCHEMA')"
dump_dir: dump
exp_logfile: meta_exp.log
exp_par_file: meta_export.par

#target metadata import parameters

imp_logfile: meta_imp.log
imp_par_file: meta_import.par